package com.example.a1111.yetingapp;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.a1111.yetingapp.musicM;

import com.example.a1111.yetingapp.musicMDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig musicMDaoConfig;

    private final musicMDao musicMDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        musicMDaoConfig = daoConfigMap.get(musicMDao.class).clone();
        musicMDaoConfig.initIdentityScope(type);

        musicMDao = new musicMDao(musicMDaoConfig, this);

        registerDao(musicM.class, musicMDao);
    }
    
    public void clear() {
        musicMDaoConfig.clearIdentityScope();
    }

    public musicMDao getMusicMDao() {
        return musicMDao;
    }

}
