package com.example.a1111.yetingapp;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MUSIC_M".
*/
public class musicMDao extends AbstractDao<musicM, String> {

    public static final String TABLENAME = "MUSIC_M";

    /**
     * Properties of entity musicM.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Imagename = new Property(2, String.class, "imagename", false, "IMAGENAME");
        public final static Property Musicplayerurl = new Property(3, String.class, "musicplayerurl", false, "MUSICPLAYERURL");
    }


    public musicMDao(DaoConfig config) {
        super(config);
    }
    
    public musicMDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MUSIC_M\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"IMAGENAME\" TEXT," + // 2: imagename
                "\"MUSICPLAYERURL\" TEXT);"); // 3: musicplayerurl
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MUSIC_M\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, musicM entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String imagename = entity.getImagename();
        if (imagename != null) {
            stmt.bindString(3, imagename);
        }
 
        String musicplayerurl = entity.getMusicplayerurl();
        if (musicplayerurl != null) {
            stmt.bindString(4, musicplayerurl);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, musicM entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String imagename = entity.getImagename();
        if (imagename != null) {
            stmt.bindString(3, imagename);
        }
 
        String musicplayerurl = entity.getMusicplayerurl();
        if (musicplayerurl != null) {
            stmt.bindString(4, musicplayerurl);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public musicM readEntity(Cursor cursor, int offset) {
        musicM entity = new musicM( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // imagename
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // musicplayerurl
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, musicM entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setImagename(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMusicplayerurl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final String updateKeyAfterInsert(musicM entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(musicM entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(musicM entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
